# Generated by Django 3.1.3 on 2021-06-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('slug', models.CharField(max_length=150, unique=True, verbose_name='Friendly URL')),
                ('visible', models.BooleanField(verbose_name='Visibility?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Made of')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
